name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push:
    branches: ["main"]
    paths-ignore:
      - "README.md"
      - "*.svg"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: SterlinkIng89
          template: classic
          base: header, activity, repositories
          config_timezone: America/Mexico_City

          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_limit: 6

          plugin_followup: yes
          plugin_followup_sections: user
